name: snookerPocket
  
services:
  mongo:
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - snooker_network

  backend:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    env_file: ./backend/.env
    networks:
      - snooker_network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      target: production
      args:
        API_URL: https://api.${DOMAIN_NAME}/api
    restart: unless-stopped
    networks:
      - snooker_network
    depends_on:
      - backend

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - snooker_network
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
networks:
  snooker_network:
    driver: bridge
